finalizada a section contact
Brener-Barbieri/Arquitetura pull request #3
Opened 2023-09-20 14:12 UTC by Brener-Barbieri

2023-09-20 14:27 UTC, antonydosreis requested changes

2023-09-20 14:27 UTC, antonydosreis commented on img/image 12.png
É uma boa prática não usar nomes de arquivos ou imagem com espaço. O que acha de colocar um `-` no lugar aqui. Ficando `image-12.png`.

2023-09-20 14:27 UTC, antonydosreis commented on index.html
> +            <input type="hidden" name="_token" value="O8F6etR7JQ4jHrVBxg0TPChIUCeyXFqEh02pfRG9">
Para que serve este campo oculto com nome `_token`?

2023-09-20 14:27 UTC, antonydosreis commented on index.html
> +            <input class="input" name="name" required="" placeholder="Name" type="text">
Quando queremos que um campo seja obrigatório. Podemos apenas passar o `required`, não sendo necessário o `=""`.

2023-09-20 14:27 UTC, antonydosreis commented on index.html
> +        <div>
Aqui podemos usar o `<picture>` também. Sempre que existir uma tag semântica de html para substituir uma div. Sempre será a melhor ideia. Das duas formas funcionam, mas usando o `<picture>` estamos com um código mais moderno

2023-09-20 14:27 UTC, antonydosreis commented on style.css
> +  color: #BDBDBD;
O que acha de colocarmos as cores em variáveis. Ia ficar mais fácil caso você precise repetir o uso delas em outros lugares.

2023-09-20 14:27 UTC, antonydosreis commented on style.css
> +.section.-contact .container .input{
Quando clicamos nos inputs, ele fica com uma `outline` azul. O que acha de colocar uma cor que condiza mais com o visual do site? Pesquisa um pouco sobre o `:focus` aqui [neste site](https://developer.mozilla.org/pt-BR/docs/Web/CSS/:focus)

2023-09-20 14:27 UTC, antonydosreis commented on style.css
> +.section.-contact .container .button-email{
No botão podemos fazer com que o mouse fique com o formato de "mãozinha apontando" quando estiver sobre ele. E também, o que acha de mudar um pouco o visual dele quando o mouse estiver por cima?

2023-09-21 17:00 UTC, Brener-Barbieri commented on style.css
> +.section.-contact .container .input{
mas aqui neste caso :focus muda a cor do texto que vai ser inserido

2023-09-21 17:03 UTC, antonydosreis commented on style.css
> +.section.-contact .container .input{
O que tem que ser feito nesse caso é como o seguinte exemplo:

```css
.classe-exemplo:focus {
    outline: 1px solid red;
}
```

2023-09-25 00:17 UTC, merged